clc;
clear all;
% load .mat file generated by Matlab app "Train Image Labeler"
load('positiveInstances_gray.mat');
names = {positiveInstances_gray(:).imageFilename};
bounds = {positiveInstances_gray(:).objectBoundingBoxes};
[~,numImg] = size(names);

% set folder for output files
Folder = 'positiveFolder/';mkdir(Folder);

for i=1:numImg
    % open file
    curFile = char(names(i));
    img = imread(curFile);
    
    % get roi reigion
    b = cat(1,bounds{1,i}); % Concatenate arrays, [x y width height]
    x = b(1); y = b(2); w = b(3); h = b(4);    
    imgroi = img(y:y+h, x:x+w, :);
    
    % extract image number from original image file name
    [~,len] = size(curFile); fileName = char();
    j = len;
    while curFile(j) ~= '\'
        fileName = strcat(curFile(j),fileName);
        j = j-1;
    end
    fileName = strcat(Folder, fileName);
    
    % write files
    imwrite(imgroi,fileName);
end